"""Print the built-in command catalog as a TypeScript module (`make catalog`).

The frontend types its action handlers as Record<CommandId, Handler>, with CommandId
taken from this generated file, so a command added to the catalog without a handler
in the web app fails `tsc`.
"""

from __future__ import annotations

import json

from app.commands.catalog import CATALOG, MACRO_ACTIONS


def main() -> None:
    commands = [
        {
            "id": c.id,
            "title": c.title,
            "category": c.category,
            "slots": list(c.slots),
            "phrase": c.phrases["en"][0],
        }
        for c in CATALOG
    ]
    print("// Generated by `make catalog` from backend/app/commands/catalog.py. Do not edit.")
    print(f"export const COMMANDS = {json.dumps(commands, indent=2, ensure_ascii=False)} as const")
    print()
    print(f"export const MACRO_ACTIONS = {json.dumps(list(MACRO_ACTIONS), indent=2)} as const")


if __name__ == "__main__":
    main()
