"""initial schema

Revision ID: cd5ade427d8b
Revises:
Create Date: 2026-09-02 20:08:35.821229
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cd5ade427d8b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The `vector` extension must exist before any VECTOR column or HNSW index is
    # created, so this is the first statement of the first migration. The
    # `pgvector/pgvector:pg17` image ships the extension files; this activates it in
    # this database. Idempotent, so re-running is safe.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessor")),
        sa.UniqueConstraint("name", name=op.f("uq_assessor_name")),
    )
    op.create_index(op.f("ix_assessor_created_at"), "assessor", ["created_at"], unique=False)
    op.create_table(
        "collection_stat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("term_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("posting_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("average_document_length", sa.Float(), server_default="0", nullable=False),
        sa.Column("index_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("log_base", sa.String(length=4), server_default="e", nullable=False),
        sa.Column("built_at", sa.DateTime(), nullable=True),
        sa.Column("build_duration_ms", sa.Float(), nullable=True),
        sa.Column("embedded_document_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_collection_stat_collection_stat_is_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_stat")),
    )
    op.create_table(
        "crawl_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seed_urls", sa.ARRAY(sa.String(length=2048)), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column("max_depth", sa.SmallInteger(), nullable=False),
        sa.Column("same_domain_only", sa.Boolean(), nullable=False),
        sa.Column("respect_robots_txt", sa.Boolean(), nullable=False),
        sa.Column("delay_seconds", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("pages_fetched", sa.Integer(), nullable=False),
        sa.Column("pages_indexed", sa.Integer(), nullable=False),
        sa.Column("pages_skipped", sa.Integer(), nullable=False),
        sa.Column("pages_failed", sa.Integer(), nullable=False),
        sa.Column("urls_discovered", sa.Integer(), nullable=False),
        sa.Column("bytes_downloaded", sa.Integer(), nullable=False),
        sa.Column("skip_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("max_depth >= 0", name=op.f("ck_crawl_job_max_depth_non_negative")),
        sa.CheckConstraint("max_pages > 0", name=op.f("ck_crawl_job_max_pages_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_job")),
    )
    op.create_index(op.f("ix_crawl_job_created_at"), "crawl_job", ["created_at"], unique=False)
    op.create_index(op.f("ix_crawl_job_status"), "crawl_job", ["status"], unique=False)
    op.create_index(op.f("ix_crawl_job_task_id"), "crawl_job", ["task_id"], unique=False)
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("source_domain", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("distinct_term_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("vector_norm", sa.Float(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.VECTOR(dim=384), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(text, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("token_count >= 0", name=op.f("ck_document_token_count_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
        sa.UniqueConstraint("url", name=op.f("uq_document_url")),
    )
    op.create_index(op.f("ix_document_content_hash"), "document", ["content_hash"], unique=False)
    op.create_index(op.f("ix_document_created_at"), "document", ["created_at"], unique=False)
    op.create_index(
        "ix_document_embedding_hnsw",
        "document",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_document_fetched_at"), "document", ["fetched_at"], unique=False)
    op.create_index(op.f("ix_document_language"), "document", ["language"], unique=False)
    op.create_index(op.f("ix_document_published_at"), "document", ["published_at"], unique=False)
    op.create_index(op.f("ix_document_simhash"), "document", ["simhash"], unique=False)
    op.create_index(op.f("ix_document_source_domain"), "document", ["source_domain"], unique=False)
    op.create_index("ix_document_tsv", "document", ["tsv"], unique=False, postgresql_using="gin")
    op.create_table(
        "lsa_model",
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.Column("components", sa.SmallInteger(), nullable=False),
        sa.Column("term_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("basis", sa.ARRAY(sa.Float()), nullable=False),
        sa.Column("singular_values", sa.ARRAY(sa.Float()), nullable=False),
        sa.Column("explained_variance_ratio", sa.Float(), nullable=False),
        sa.Column("built_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("index_version", name=op.f("pk_lsa_model")),
    )
    op.create_table(
        "robots_cache",
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("fetched", sa.Boolean(), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("crawl_delay", sa.Float(), nullable=True),
        sa.Column("sitemaps", sa.ARRAY(sa.String(length=2048)), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("host", name=op.f("pk_robots_cache")),
    )
    op.create_index(
        op.f("ix_robots_cache_created_at"), "robots_cache", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_robots_cache_expires_at"), "robots_cache", ["expires_at"], unique=False
    )
    op.create_table(
        "search_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("query_text", sa.String(length=512), nullable=False),
        sa.Column("query_lemmas", sa.ARRAY(sa.String(length=64)), nullable=True),
        sa.Column("ranker", sa.String(length=16), nullable=False),
        sa.Column("all_words_together", sa.Boolean(), nullable=False),
        sa.Column("date_from", sa.DateTime(), nullable=True),
        sa.Column("date_to", sa.DateTime(), nullable=True),
        sa.Column("candidates_considered", sa.Integer(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("top_score", sa.Float(), nullable=True),
        sa.Column("stage_timings_ms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_log")),
    )
    op.create_index(op.f("ix_search_log_created_at"), "search_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_search_log_ranker"), "search_log", ["ranker"], unique=False)
    op.create_index(
        "ix_search_log_ranker_created", "search_log", ["ranker", "created_at"], unique=False
    )
    op.create_table(
        "term",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lemma", sa.String(length=64), nullable=False),
        sa.Column("pos", sa.String(length=16), nullable=True),
        sa.Column("document_frequency", sa.Integer(), nullable=False),
        sa.Column("collection_frequency", sa.Integer(), nullable=False),
        sa.Column("idf", sa.Float(), nullable=False),
        sa.CheckConstraint("document_frequency >= 0", name=op.f("ck_term_df_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_term")),
        sa.UniqueConstraint("lemma", name=op.f("uq_term_lemma")),
    )
    op.create_index("ix_term_document_frequency", "term", ["document_frequency"], unique=False)
    op.create_index(op.f("ix_term_pos"), "term", ["pos"], unique=False)
    op.create_table(
        "test_collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_collection")),
        sa.UniqueConstraint("name", name=op.f("uq_test_collection_name")),
    )
    op.create_index(
        op.f("ix_test_collection_created_at"), "test_collection", ["created_at"], unique=False
    )
    op.create_table(
        "crawl_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("url_canonical", sa.String(length=2048), nullable=False),
        sa.Column("depth", sa.SmallInteger(), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("skip_reason", sa.String(length=32), nullable=True),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("discovered_from", sa.Integer(), nullable=True),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("stage_timings_ms", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_bytes", sa.Integer(), nullable=True),
        sa.Column("extracted_chars", sa.Integer(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["discovered_from"],
            ["crawl_task.id"],
            name=op.f("fk_crawl_task_discovered_from_crawl_task"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_crawl_task_document_id_document"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["crawl_job.id"],
            name=op.f("fk_crawl_task_job_id_crawl_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_task")),
        sa.UniqueConstraint("job_id", "url_canonical", name="uq_crawl_task_job_url"),
    )
    op.create_index(
        "ix_crawl_task_claim",
        "crawl_task",
        ["job_id", "priority", "depth", "id"],
        unique=False,
        postgresql_where="status = 'pending'",
    )
    op.create_index("ix_crawl_task_job_status", "crawl_task", ["job_id", "status"], unique=False)
    op.create_table(
        "lsa_projection",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("z", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_lsa_projection_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("document_id", name=op.f("pk_lsa_projection")),
    )
    op.create_index(
        "ix_lsa_projection_index_version", "lsa_projection", ["index_version"], unique=False
    )
    op.create_table(
        "posting",
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("term_frequency", sa.Integer(), nullable=False),
        sa.Column("weight_raw", sa.Float(), nullable=False),
        sa.Column("weight_norm", sa.Float(), nullable=False),
        sa.Column("positions", sa.ARRAY(sa.Integer()), nullable=True),
        sa.CheckConstraint("term_frequency > 0", name=op.f("ck_posting_tf_positive")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_posting_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"], ["term.id"], name=op.f("fk_posting_term_id_term"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("term_id", "document_id", name=op.f("pk_posting")),
    )
    op.create_index("ix_posting_document_id", "posting", ["document_id"], unique=False)
    op.create_index(
        "ix_posting_term_weight",
        "posting",
        ["term_id", "weight_norm"],
        unique=False,
        postgresql_where="weight_norm > 0",
    )
    op.create_table(
        "qrel_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("aggregation", sa.String(length=4), nullable=False),
        sa.Column("threshold", sa.SmallInteger(), nullable=False),
        sa.Column("query_count", sa.Integer(), nullable=False),
        sa.Column("relevant_count", sa.Integer(), nullable=False),
        sa.Column("judged_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "threshold BETWEEN 0 AND 3", name=op.f("ck_qrel_set_threshold_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["test_collection.id"],
            name=op.f("fk_qrel_set_collection_id_test_collection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qrel_set")),
        sa.UniqueConstraint(
            "collection_id",
            "aggregation",
            "threshold",
            name="uq_qrel_set_collection_aggregation_threshold",
        ),
    )
    op.create_index(op.f("ix_qrel_set_created_at"), "qrel_set", ["created_at"], unique=False)
    op.create_table(
        "query",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("ext_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("is_judged", sa.Boolean(), nullable=False),
        sa.Column("selected_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["test_collection.id"],
            name=op.f("fk_query_collection_id_test_collection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_query")),
        sa.UniqueConstraint("collection_id", "ext_id", name="uq_query_collection_ext"),
    )
    op.create_index(op.f("ix_query_category"), "query", ["category"], unique=False)
    op.create_index(op.f("ix_query_created_at"), "query", ["created_at"], unique=False)
    op.create_index(op.f("ix_query_is_judged"), "query", ["is_judged"], unique=False)
    op.create_table(
        "eval_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("qrel_set_id", sa.Integer(), nullable=False),
        sa.Column("ranker", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("top_k", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("params_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("scored_query_count", sa.Integer(), nullable=False),
        sa.Column("unjudged_retrieved", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["test_collection.id"],
            name=op.f("fk_eval_run_collection_id_test_collection"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["qrel_set_id"],
            ["qrel_set.id"],
            name=op.f("fk_eval_run_qrel_set_id_qrel_set"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_run")),
    )
    op.create_index(op.f("ix_eval_run_created_at"), "eval_run", ["created_at"], unique=False)
    op.create_index(op.f("ix_eval_run_ranker"), "eval_run", ["ranker"], unique=False)
    op.create_table(
        "feedback_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_query", sa.String(length=512), nullable=False),
        sa.Column("ranker", sa.String(length=16), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=True),
        sa.Column("alpha", sa.Float(), nullable=False),
        sa.Column("beta", sa.Float(), nullable=False),
        sa.Column("gamma", sa.Float(), nullable=False),
        sa.Column("iteration_count", sa.SmallInteger(), nullable=False),
        sa.Column("iterations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.id"],
            name=op.f("fk_feedback_session_query_id_query"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_session")),
    )
    op.create_index(
        op.f("ix_feedback_session_created_at"), "feedback_session", ["created_at"], unique=False
    )
    op.create_table(
        "judgment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("assessor_id", sa.Integer(), nullable=False),
        sa.Column("grade", sa.String(length=16), nullable=False),
        sa.Column("seconds_spent", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessor_id"],
            ["assessor.id"],
            name=op.f("fk_judgment_assessor_id_assessor"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_judgment_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["query_id"], ["query.id"], name=op.f("fk_judgment_query_id_query"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_judgment")),
        sa.UniqueConstraint(
            "query_id", "document_id", "assessor_id", name="uq_judgment_pair_assessor"
        ),
    )
    op.create_index(op.f("ix_judgment_created_at"), "judgment", ["created_at"], unique=False)
    op.create_index(
        "ix_judgment_query_document", "judgment", ["query_id", "document_id"], unique=False
    )
    op.create_table(
        "pool_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("pool_depth", sa.SmallInteger(), nullable=True),
        sa.Column("contributed_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_pool_entry_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.id"],
            name=op.f("fk_pool_entry_query_id_query"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pool_entry")),
        sa.UniqueConstraint("query_id", "document_id", name="uq_pool_entry_query_document"),
    )
    op.create_index(op.f("ix_pool_entry_created_at"), "pool_entry", ["created_at"], unique=False)
    op.create_index(
        "ix_pool_entry_query_source", "pool_entry", ["query_id", "source"], unique=False
    )
    op.create_table(
        "qrel",
        sa.Column("qrel_set_id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("is_relevant", sa.Boolean(), nullable=False),
        sa.Column("gain", sa.Float(), nullable=False),
        sa.Column("is_unjudged", sa.Boolean(), nullable=False),
        sa.Column("assessor_count", sa.SmallInteger(), nullable=False),
        sa.Column("has_disagreement", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_qrel_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["qrel_set_id"],
            ["qrel_set.id"],
            name=op.f("fk_qrel_qrel_set_id_qrel_set"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["query_id"], ["query.id"], name=op.f("fk_qrel_query_id_query"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("qrel_set_id", "query_id", "document_id", name=op.f("pk_qrel")),
    )
    op.create_index(
        "ix_qrel_relevant",
        "qrel",
        ["qrel_set_id", "query_id"],
        unique=False,
        postgresql_where="is_relevant",
    )
    op.create_table(
        "run_curve",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("curve_key", sa.String(length=32), nullable=False),
        sa.Column("points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("support", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["eval_run.id"],
            name=op.f("fk_run_curve_run_id_eval_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", "curve_key", name=op.f("pk_run_curve")),
    )
    op.create_table(
        "run_metric",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("metric_key", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("query_count", sa.Integer(), nullable=False),
        sa.Column("averaging", sa.String(length=8), nullable=False),
        sa.Column("ci_low", sa.Float(), nullable=True),
        sa.Column("ci_high", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["eval_run.id"],
            name=op.f("fk_run_metric_run_id_eval_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", "metric_key", name=op.f("pk_run_metric")),
    )
    op.create_table(
        "run_query_curve",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("curve_key", sa.String(length=32), nullable=False),
        sa.Column("points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.id"],
            name=op.f("fk_run_query_curve_query_id_query"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["eval_run.id"],
            name=op.f("fk_run_query_curve_run_id_eval_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", "query_id", "curve_key", name=op.f("pk_run_query_curve")),
    )
    op.create_table(
        "run_query_metric",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("metric_key", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.id"],
            name=op.f("fk_run_query_metric_query_id_query"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["eval_run.id"],
            name=op.f("fk_run_query_metric_run_id_eval_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "query_id", "metric_key", name=op.f("pk_run_query_metric")
        ),
    )
    op.create_index(
        "ix_run_query_metric_key", "run_query_metric", ["run_id", "metric_key"], unique=False
    )
    op.create_table(
        "run_result",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_run_result_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.id"],
            name=op.f("fk_run_result_query_id_query"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["eval_run.id"],
            name=op.f("fk_run_result_run_id_eval_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", "query_id", "rank", name=op.f("pk_run_result")),
    )
    op.create_index("ix_run_result_run_query", "run_result", ["run_id", "query_id"], unique=False)
    op.create_table(
        "significance_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_a_id", sa.Integer(), nullable=False),
        sa.Column("run_b_id", sa.Integer(), nullable=False),
        sa.Column("metric_key", sa.String(length=32), nullable=False),
        sa.Column("test", sa.String(length=16), nullable=False),
        sa.Column("statistic", sa.Float(), nullable=True),
        sa.Column("p_value", sa.Float(), nullable=False),
        sa.Column("p_value_corrected", sa.Float(), nullable=True),
        sa.Column("correction", sa.String(length=16), nullable=True),
        sa.Column("mean_difference", sa.Float(), nullable=False),
        sa.Column("effect_size", sa.Float(), nullable=True),
        sa.Column("ci_low", sa.Float(), nullable=True),
        sa.Column("ci_high", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "run_a_id <> run_b_id", name=op.f("ck_significance_result_significance_distinct_runs")
        ),
        sa.ForeignKeyConstraint(
            ["run_a_id"],
            ["eval_run.id"],
            name=op.f("fk_significance_result_run_a_id_eval_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_b_id"],
            ["eval_run.id"],
            name=op.f("fk_significance_result_run_b_id_eval_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_significance_result")),
        sa.UniqueConstraint(
            "run_a_id", "run_b_id", "metric_key", "test", name="uq_significance_pair"
        ),
    )
    op.create_index(
        op.f("ix_significance_result_created_at"),
        "significance_result",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # `collection_stat` is a singleton guarded by a `id = 1` check constraint. Seeding it
    # here lets every later query assume it exists, instead of every caller handling the
    # "index has never been built" case separately.
    op.execute(
        "INSERT INTO collection_stat (id) VALUES (1) ON CONFLICT (id) DO NOTHING"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_significance_result_created_at"), table_name="significance_result")
    op.drop_table("significance_result")
    op.drop_index("ix_run_result_run_query", table_name="run_result")
    op.drop_table("run_result")
    op.drop_index("ix_run_query_metric_key", table_name="run_query_metric")
    op.drop_table("run_query_metric")
    op.drop_table("run_query_curve")
    op.drop_table("run_metric")
    op.drop_table("run_curve")
    op.drop_index("ix_qrel_relevant", table_name="qrel", postgresql_where="is_relevant")
    op.drop_table("qrel")
    op.drop_index("ix_pool_entry_query_source", table_name="pool_entry")
    op.drop_index(op.f("ix_pool_entry_created_at"), table_name="pool_entry")
    op.drop_table("pool_entry")
    op.drop_index("ix_judgment_query_document", table_name="judgment")
    op.drop_index(op.f("ix_judgment_created_at"), table_name="judgment")
    op.drop_table("judgment")
    op.drop_index(op.f("ix_feedback_session_created_at"), table_name="feedback_session")
    op.drop_table("feedback_session")
    op.drop_index(op.f("ix_eval_run_ranker"), table_name="eval_run")
    op.drop_index(op.f("ix_eval_run_created_at"), table_name="eval_run")
    op.drop_table("eval_run")
    op.drop_index(op.f("ix_query_is_judged"), table_name="query")
    op.drop_index(op.f("ix_query_created_at"), table_name="query")
    op.drop_index(op.f("ix_query_category"), table_name="query")
    op.drop_table("query")
    op.drop_index(op.f("ix_qrel_set_created_at"), table_name="qrel_set")
    op.drop_table("qrel_set")
    op.drop_index(
        "ix_posting_term_weight", table_name="posting", postgresql_where="weight_norm > 0"
    )
    op.drop_index("ix_posting_document_id", table_name="posting")
    op.drop_table("posting")
    op.drop_index("ix_lsa_projection_index_version", table_name="lsa_projection")
    op.drop_table("lsa_projection")
    op.drop_index("ix_crawl_task_job_status", table_name="crawl_task")
    op.drop_index(
        "ix_crawl_task_claim", table_name="crawl_task", postgresql_where="status = 'pending'"
    )
    op.drop_table("crawl_task")
    op.drop_index(op.f("ix_test_collection_created_at"), table_name="test_collection")
    op.drop_table("test_collection")
    op.drop_index(op.f("ix_term_pos"), table_name="term")
    op.drop_index("ix_term_document_frequency", table_name="term")
    op.drop_table("term")
    op.drop_index("ix_search_log_ranker_created", table_name="search_log")
    op.drop_index(op.f("ix_search_log_ranker"), table_name="search_log")
    op.drop_index(op.f("ix_search_log_created_at"), table_name="search_log")
    op.drop_table("search_log")
    op.drop_index(op.f("ix_robots_cache_expires_at"), table_name="robots_cache")
    op.drop_index(op.f("ix_robots_cache_created_at"), table_name="robots_cache")
    op.drop_table("robots_cache")
    op.drop_table("lsa_model")
    op.drop_index("ix_document_tsv", table_name="document", postgresql_using="gin")
    op.drop_index(op.f("ix_document_source_domain"), table_name="document")
    op.drop_index(op.f("ix_document_simhash"), table_name="document")
    op.drop_index(op.f("ix_document_published_at"), table_name="document")
    op.drop_index(op.f("ix_document_language"), table_name="document")
    op.drop_index(op.f("ix_document_fetched_at"), table_name="document")
    op.drop_index(
        "ix_document_embedding_hnsw",
        table_name="document",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_document_created_at"), table_name="document")
    op.drop_index(op.f("ix_document_content_hash"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_crawl_job_task_id"), table_name="crawl_job")
    op.drop_index(op.f("ix_crawl_job_status"), table_name="crawl_job")
    op.drop_index(op.f("ix_crawl_job_created_at"), table_name="crawl_job")
    op.drop_table("crawl_job")
    op.drop_table("collection_stat")
    op.drop_index(op.f("ix_assessor_created_at"), table_name="assessor")
    op.drop_table("assessor")
    # ### end Alembic commands ###

    # NOTE: the `vector` extension is intentionally left in place —
    # dropping it would cascade into any other schema using it.
