// Generated by `make catalog` from backend/app/commands/catalog.py. Do not edit.
export const COMMANDS = [
  {
    "id": "play",
    "title": "Play",
    "category": "playback",
    "slots": [],
    "phrase": "play"
  },
  {
    "id": "pause",
    "title": "Pause",
    "category": "playback",
    "slots": [],
    "phrase": "pause"
  },
  {
    "id": "resume",
    "title": "Resume",
    "category": "playback",
    "slots": [],
    "phrase": "resume"
  },
  {
    "id": "stop",
    "title": "Stop",
    "category": "playback",
    "slots": [],
    "phrase": "stop"
  },
  {
    "id": "repeat",
    "title": "Repeat",
    "category": "playback",
    "slots": [],
    "phrase": "repeat"
  },
  {
    "id": "start_over",
    "title": "Start over",
    "category": "playback",
    "slots": [],
    "phrase": "start over"
  },
  {
    "id": "next_sentence",
    "title": "Next sentence",
    "category": "navigation",
    "slots": [],
    "phrase": "next"
  },
  {
    "id": "previous_sentence",
    "title": "Previous sentence",
    "category": "navigation",
    "slots": [],
    "phrase": "back"
  },
  {
    "id": "next_paragraph",
    "title": "Next paragraph",
    "category": "navigation",
    "slots": [],
    "phrase": "next paragraph"
  },
  {
    "id": "previous_paragraph",
    "title": "Previous paragraph",
    "category": "navigation",
    "slots": [],
    "phrase": "previous paragraph"
  },
  {
    "id": "next_section",
    "title": "Next section",
    "category": "navigation",
    "slots": [],
    "phrase": "next section"
  },
  {
    "id": "go_to_section",
    "title": "Go to section",
    "category": "navigation",
    "slots": [
      "number",
      "section"
    ],
    "phrase": "go to section {number}"
  },
  {
    "id": "read_abstract",
    "title": "Read the abstract",
    "category": "navigation",
    "slots": [],
    "phrase": "read the abstract"
  },
  {
    "id": "faster",
    "title": "Faster",
    "category": "voice",
    "slots": [],
    "phrase": "faster"
  },
  {
    "id": "slower",
    "title": "Slower",
    "category": "voice",
    "slots": [],
    "phrase": "slower"
  },
  {
    "id": "set_speed",
    "title": "Set speed",
    "category": "voice",
    "slots": [
      "number"
    ],
    "phrase": "speed {number}"
  },
  {
    "id": "normal_speed",
    "title": "Normal speed",
    "category": "voice",
    "slots": [],
    "phrase": "normal speed"
  },
  {
    "id": "louder",
    "title": "Louder",
    "category": "voice",
    "slots": [],
    "phrase": "louder"
  },
  {
    "id": "quieter",
    "title": "Quieter",
    "category": "voice",
    "slots": [],
    "phrase": "quieter"
  },
  {
    "id": "mute",
    "title": "Mute",
    "category": "voice",
    "slots": [],
    "phrase": "mute"
  },
  {
    "id": "unmute",
    "title": "Unmute",
    "category": "voice",
    "slots": [],
    "phrase": "unmute"
  },
  {
    "id": "next_voice",
    "title": "Next voice",
    "category": "voice",
    "slots": [],
    "phrase": "next voice"
  },
  {
    "id": "switch_voice",
    "title": "Switch voice",
    "category": "voice",
    "slots": [
      "voice"
    ],
    "phrase": "switch to {voice}"
  },
  {
    "id": "male_voice",
    "title": "Male voice",
    "category": "voice",
    "slots": [],
    "phrase": "male voice"
  },
  {
    "id": "female_voice",
    "title": "Female voice",
    "category": "voice",
    "slots": [],
    "phrase": "female voice"
  },
  {
    "id": "british_accent",
    "title": "British accent",
    "category": "voice",
    "slots": [],
    "phrase": "british accent"
  },
  {
    "id": "american_accent",
    "title": "American accent",
    "category": "voice",
    "slots": [],
    "phrase": "american accent"
  },
  {
    "id": "where_am_i",
    "title": "Where am I",
    "category": "assistant",
    "slots": [],
    "phrase": "where am i"
  },
  {
    "id": "time_left",
    "title": "Time left",
    "category": "assistant",
    "slots": [],
    "phrase": "how much is left"
  },
  {
    "id": "explain",
    "title": "Explain a term",
    "category": "assistant",
    "slots": [
      "term"
    ],
    "phrase": "explain {term}"
  },
  {
    "id": "summarize",
    "title": "Summarize section",
    "category": "assistant",
    "slots": [],
    "phrase": "summarize"
  },
  {
    "id": "read_clipboard",
    "title": "Read clipboard",
    "category": "app",
    "slots": [],
    "phrase": "read clipboard"
  },
  {
    "id": "new_document",
    "title": "New document",
    "category": "app",
    "slots": [],
    "phrase": "new document"
  },
  {
    "id": "open_library",
    "title": "Open library",
    "category": "app",
    "slots": [],
    "phrase": "open library"
  },
  {
    "id": "dark_mode",
    "title": "Dark mode",
    "category": "app",
    "slots": [],
    "phrase": "dark mode"
  },
  {
    "id": "light_mode",
    "title": "Light mode",
    "category": "app",
    "slots": [],
    "phrase": "light mode"
  },
  {
    "id": "show_commands",
    "title": "What can I say",
    "category": "app",
    "slots": [],
    "phrase": "what can i say"
  },
  {
    "id": "stop_listening",
    "title": "Stop listening",
    "category": "app",
    "slots": [],
    "phrase": "stop listening"
  }
] as const

export const MACRO_ACTIONS = [
  "play",
  "pause",
  "resume",
  "stop",
  "repeat",
  "start_over",
  "next_sentence",
  "previous_sentence",
  "next_paragraph",
  "previous_paragraph",
  "next_section",
  "go_to_section",
  "read_abstract",
  "set_speed",
  "normal_speed",
  "faster",
  "slower",
  "louder",
  "quieter",
  "set_volume",
  "mute",
  "unmute",
  "switch_voice",
  "next_voice",
  "set_pitch",
  "where_am_i",
  "time_left",
  "summarize",
  "read_clipboard",
  "open_library",
  "dark_mode",
  "light_mode",
  "show_commands",
  "stop_listening",
  "say"
] as const
