"""The built-in voice commands: what Lector can do, and how to ask for it in four languages.

Each command names one *action* the web app executes. Phrases may contain slots:

* ``{number}`` - an integer or decimal ("section 3", "speed 1.5")
* ``{section}`` - free text resolved against the current document's section titles
* ``{voice}`` - a voice name ("Emma", "George")
* ``{term}`` - free text, passed to the assistant ("explain {term}")

Users can switch commands off, replace their phrases per language and add their own
commands (macros of these actions); those edits live in the database, this catalog
stays the versioned default. `make catalog` exports it for the frontend's type check.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

Category = Literal["playback", "navigation", "voice", "assistant", "app"]
Slot = Literal["number", "section", "voice", "term"]
LANGUAGES = ("en", "ru", "de", "fr")


@dataclass(frozen=True)
class Command:
    id: str
    title: str
    category: Category
    description: str
    phrases: dict[str, tuple[str, ...]]
    slots: tuple[Slot, ...] = ()
    reply: str = ""  # short spoken confirmation, English; {slot} placeholders allowed
    needs_llm: bool = False
    params: dict[str, str] = field(default_factory=dict)  # for custom macros: param -> type


def _c(
    id: str,
    title: str,
    category: Category,
    description: str,
    *,
    en: tuple[str, ...],
    ru: tuple[str, ...],
    de: tuple[str, ...],
    fr: tuple[str, ...],
    slots: tuple[Slot, ...] = (),
    reply: str = "",
    needs_llm: bool = False,
    params: dict[str, str] | None = None,
) -> Command:
    return Command(
        id,
        title,
        category,
        description,
        {"en": en, "ru": ru, "de": de, "fr": fr},
        slots,
        reply,
        needs_llm,
        params or {},
    )


CATALOG: tuple[Command, ...] = (
    # ---------------------------------------------------------------- playback
    _c(
        "play",
        "Play",
        "playback",
        "Start reading from the current sentence",
        en=("play", "read", "start reading", "read aloud", "read to me", "go"),
        ru=("читай", "читать", "начни читать", "прочитай", "поехали", "воспроизведи"),
        de=("lies", "vorlesen", "lies vor", "starte", "abspielen", "los"),
        fr=("lis", "lire", "commence à lire", "lecture", "vas-y"),
        reply="Reading",
    ),
    _c(
        "pause",
        "Pause",
        "playback",
        "Pause reading",
        en=("pause", "wait", "hold on", "hold", "pause reading"),
        ru=("пауза", "подожди", "стоп пауза", "погоди", "поставь на паузу"),
        de=("pause", "warte", "moment", "anhalten"),
        fr=("pause", "attends", "mets en pause", "une seconde"),
        reply="Paused",
    ),
    _c(
        "resume",
        "Resume",
        "playback",
        "Continue after a pause",
        en=("resume", "continue", "go on", "keep reading", "carry on", "unpause"),
        ru=("продолжай", "продолжи", "дальше читай", "продолжить"),
        de=("weiter", "fortsetzen", "mach weiter", "lies weiter"),
        fr=("reprends", "continue", "continuer", "reprendre"),
        reply="Continuing",
    ),
    _c(
        "stop",
        "Stop",
        "playback",
        "Stop reading and rewind to the current sentence",
        en=("stop", "stop reading", "that's enough", "quiet", "silence", "shut up"),
        ru=("стоп", "хватит", "остановись", "замолчи", "перестань"),
        de=("stopp", "stop", "hör auf", "genug", "ruhe"),
        fr=("stop", "arrête", "arrête de lire", "silence", "tais-toi"),
        reply="Stopped",
    ),
    _c(
        "repeat",
        "Repeat",
        "playback",
        "Read the current sentence again",
        en=(
            "repeat",
            "again",
            "say that again",
            "repeat that",
            "one more time",
            "what did you say",
        ),
        ru=("повтори", "ещё раз", "повтори это", "что ты сказал"),
        de=("wiederholen", "nochmal", "noch einmal", "wiederhole das"),
        fr=("répète", "encore", "encore une fois", "répète ça"),
        reply="",
    ),
    _c(
        "start_over",
        "Start over",
        "playback",
        "Read the document from the beginning",
        en=(
            "start over",
            "from the beginning",
            "start from the beginning",
            "restart",
            "read from the top",
        ),
        ru=("сначала", "с начала", "начни сначала", "читай с начала"),
        de=("von vorne", "von anfang an", "neu starten", "nochmal von vorne"),
        fr=("depuis le début", "recommence", "reprends depuis le début", "au début"),
        reply="From the beginning",
    ),
    # -------------------------------------------------------------- navigation
    _c(
        "next_sentence",
        "Next sentence",
        "navigation",
        "Skip to the next sentence",
        en=("next", "next sentence", "skip", "skip this", "forward"),
        ru=("дальше", "следующее", "следующее предложение", "пропусти"),
        de=("nächster", "nächster satz", "überspringen", "weiter vor"),
        fr=("suivant", "phrase suivante", "passe", "saute"),
        reply="",
    ),
    _c(
        "previous_sentence",
        "Previous sentence",
        "navigation",
        "Go back one sentence",
        en=("back", "go back", "previous", "previous sentence", "back one"),
        ru=("назад", "предыдущее", "предыдущее предложение", "вернись"),
        de=("zurück", "vorheriger satz", "geh zurück"),
        fr=("retour", "précédent", "phrase précédente", "reviens"),
        reply="",
    ),
    _c(
        "next_paragraph",
        "Next paragraph",
        "navigation",
        "Jump to the next paragraph",
        en=("next paragraph", "skip paragraph", "skip this paragraph"),
        ru=("следующий абзац", "пропусти абзац", "дальше абзац"),
        de=("nächster absatz", "absatz überspringen"),
        fr=("paragraphe suivant", "saute le paragraphe"),
        reply="",
    ),
    _c(
        "previous_paragraph",
        "Previous paragraph",
        "navigation",
        "Go back to the previous paragraph",
        en=("previous paragraph", "last paragraph", "back a paragraph", "paragraph back"),
        ru=("предыдущий абзац", "абзац назад"),
        de=("vorheriger absatz", "absatz zurück"),
        fr=("paragraphe précédent",),
        reply="",
    ),
    _c(
        "next_section",
        "Next section",
        "navigation",
        "Jump to the next section",
        en=("next section", "skip section", "skip this section", "next chapter"),
        ru=("следующий раздел", "пропусти раздел", "следующая глава"),
        de=("nächster abschnitt", "abschnitt überspringen", "nächstes kapitel"),
        fr=("section suivante", "saute la section", "chapitre suivant"),
        reply="",
    ),
    _c(
        "go_to_section",
        "Go to section",
        "navigation",
        "Jump to a section by number or name",
        en=(
            "go to section {number}",
            "section {number}",
            "read section {number}",
            "jump to section {number}",
            "go to {section}",
            "read the {section}",
            "jump to {section}",
            "read {section} section",
            "go to the {section}",
        ),
        ru=(
            "раздел {number}",
            "перейди к разделу {number}",
            "читай раздел {number}",
            "перейди к {section}",
            "читай {section}",
        ),
        de=(
            "abschnitt {number}",
            "gehe zu abschnitt {number}",
            "lies abschnitt {number}",
            "gehe zu {section}",
            "lies {section}",
        ),
        fr=(
            "section {number}",
            "va à la section {number}",
            "lis la section {number}",
            "va à {section}",
            "lis {section}",
        ),
        slots=("number", "section"),
        reply="{section_title}",
    ),
    _c(
        "read_abstract",
        "Read the abstract",
        "navigation",
        "Jump to the abstract",
        en=("read the abstract", "abstract", "go to the abstract", "what is this paper about"),
        ru=("читай аннотацию", "аннотация", "о чём статья"),
        de=("lies die zusammenfassung", "zusammenfassung", "abstract"),
        fr=("lis le résumé", "résumé", "de quoi parle l'article"),
        reply="Abstract",
    ),
    # ------------------------------------------------------------------ voice
    _c(
        "faster",
        "Faster",
        "voice",
        "Speed up by 10%",
        en=("faster", "speed up", "read faster", "go faster", "a bit faster", "quicker"),
        ru=("быстрее", "ускорь", "читай быстрее", "побыстрее"),
        de=("schneller", "schneller lesen", "beschleunigen"),
        fr=("plus vite", "accélère", "lis plus vite"),
        reply="Speed {speed}",
    ),
    _c(
        "slower",
        "Slower",
        "voice",
        "Slow down by 10%",
        en=("slower", "slow down", "read slower", "go slower", "a bit slower", "not so fast"),
        ru=("медленнее", "помедленнее", "читай медленнее", "не так быстро", "замедли"),
        de=("langsamer", "langsamer lesen", "nicht so schnell"),
        fr=("moins vite", "plus lentement", "ralentis", "pas si vite"),
        reply="Speed {speed}",
    ),
    _c(
        "set_speed",
        "Set speed",
        "voice",
        "Set the reading speed (0.5–2.0)",
        en=(
            "speed {number}",
            "set speed to {number}",
            "set the speed to {number}",
            "read at {number}",
        ),
        ru=("скорость {number}", "поставь скорость {number}"),
        de=("geschwindigkeit {number}", "tempo {number}"),
        fr=("vitesse {number}", "règle la vitesse à {number}"),
        slots=("number",),
        reply="Speed {speed}",
    ),
    _c(
        "normal_speed",
        "Normal speed",
        "voice",
        "Reset the speed to 1.0",
        en=("normal speed", "reset speed", "regular speed", "default speed"),
        ru=("обычная скорость", "нормальная скорость", "сбрось скорость"),
        de=("normale geschwindigkeit", "normales tempo"),
        fr=("vitesse normale", "vitesse par défaut"),
        reply="Normal speed",
    ),
    _c(
        "louder",
        "Louder",
        "voice",
        "Increase the volume",
        en=("louder", "volume up", "speak up", "turn it up", "increase volume"),
        ru=("громче", "прибавь громкость", "погромче"),
        de=("lauter", "lauter bitte", "lautstärke hoch"),
        fr=("plus fort", "monte le son", "augmente le volume"),
        reply="Volume {volume}",
    ),
    _c(
        "quieter",
        "Quieter",
        "voice",
        "Decrease the volume",
        en=("quieter", "volume down", "softer", "turn it down", "lower the volume"),
        ru=("тише", "убавь громкость", "потише"),
        de=("leiser", "lautstärke runter"),
        fr=("moins fort", "baisse le son", "baisse le volume"),
        reply="Volume {volume}",
    ),
    _c(
        "mute",
        "Mute",
        "voice",
        "Mute the voice without pausing",
        en=("mute", "mute voice", "sound off"),
        ru=("выключи звук", "без звука"),
        de=("stumm", "ton aus"),
        fr=("muet", "coupe le son"),
        reply="",
    ),
    _c(
        "unmute",
        "Unmute",
        "voice",
        "Unmute",
        en=("unmute", "sound on"),
        ru=("включи звук",),
        de=("ton an", "stumm aus"),
        fr=("remets le son",),
        reply="Sound on",
    ),
    _c(
        "next_voice",
        "Next voice",
        "voice",
        "Switch to the next voice",
        en=("next voice", "change voice", "another voice", "different voice", "switch voice"),
        ru=("другой голос", "смени голос", "следующий голос"),
        de=("nächste stimme", "andere stimme", "stimme wechseln"),
        fr=("voix suivante", "change de voix", "autre voix"),
        reply="This is {voice}",
    ),
    _c(
        "switch_voice",
        "Switch voice",
        "voice",
        "Switch to a voice by name",
        en=(
            "switch to {voice}",
            "use {voice}",
            "voice {voice}",
            "change voice to {voice}",
            "let {voice} read",
        ),
        ru=("голос {voice}", "переключись на {voice}"),
        de=("stimme {voice}", "wechsle zu {voice}"),
        fr=("voix {voice}", "passe à {voice}"),
        slots=("voice",),
        reply="This is {voice}",
    ),
    _c(
        "male_voice",
        "Male voice",
        "voice",
        "Switch to a male voice",
        en=("male voice", "man's voice", "a male voice"),
        ru=("мужской голос",),
        de=("männliche stimme",),
        fr=("voix masculine", "voix d'homme"),
        reply="This is {voice}",
    ),
    _c(
        "female_voice",
        "Female voice",
        "voice",
        "Switch to a female voice",
        en=("female voice", "woman's voice", "a female voice"),
        ru=("женский голос",),
        de=("weibliche stimme",),
        fr=("voix féminine", "voix de femme"),
        reply="This is {voice}",
    ),
    _c(
        "british_accent",
        "British accent",
        "voice",
        "Switch to a British English voice",
        en=("british accent", "british voice", "british english"),
        ru=("британский акцент", "британский голос"),
        de=("britischer akzent", "britische stimme"),
        fr=("accent britannique", "voix britannique"),
        reply="This is {voice}",
    ),
    _c(
        "american_accent",
        "American accent",
        "voice",
        "Switch to an American English voice",
        en=("american accent", "american voice", "american english"),
        ru=("американский акцент", "американский голос"),
        de=("amerikanischer akzent", "amerikanische stimme"),
        fr=("accent américain", "voix américaine"),
        reply="This is {voice}",
    ),
    # -------------------------------------------------------------- assistant
    _c(
        "where_am_i",
        "Where am I",
        "assistant",
        "Say the current section and progress",
        en=("where am i", "what section is this", "which section", "where are we"),
        ru=("где я", "какой это раздел", "где мы"),
        de=("wo bin ich", "welcher abschnitt"),
        fr=("où suis-je", "quelle section", "où en est-on"),
        reply="{where}",
    ),
    _c(
        "time_left",
        "Time left",
        "assistant",
        "Say how long the rest of the document takes",
        en=("how much is left", "time left", "how long is left", "how long until the end"),
        ru=("сколько осталось", "сколько ещё"),
        de=("wie viel noch", "wie lange noch"),
        fr=("combien de temps reste", "combien reste-t-il"),
        reply="{time_left}",
    ),
    _c(
        "explain",
        "Explain a term",
        "assistant",
        "Explain a term using the paper as context",
        en=(
            "explain {term}",
            "what is {term}",
            "what does {term} mean",
            "define {term}",
            "what are {term}",
            "tell me about {term}",
        ),
        ru=("объясни {term}", "что такое {term}", "что значит {term}"),
        de=("erkläre {term}", "was ist {term}", "was bedeutet {term}"),
        fr=("explique {term}", "qu'est-ce que {term}", "que signifie {term}"),
        slots=("term",),
        needs_llm=True,
        reply="",
    ),
    _c(
        "summarize",
        "Summarize section",
        "assistant",
        "Summarize the current section",
        en=(
            "summarize",
            "summarize this section",
            "give me a summary",
            "summary",
            "tl dr",
            "sum it up",
        ),
        ru=("перескажи", "кратко", "краткое содержание", "подведи итог"),
        de=("fasse zusammen", "zusammenfassen", "kurzfassung"),
        fr=("résume", "résume cette section", "fais un résumé"),
        needs_llm=True,
        reply="",
    ),
    # --------------------------------------------------------------------- app
    _c(
        "read_clipboard",
        "Read clipboard",
        "app",
        "Read the text on the clipboard",
        en=("read clipboard", "read the clipboard", "read what i copied", "paste and read"),
        ru=("читай буфер", "прочитай буфер обмена", "прочитай скопированное"),
        de=("zwischenablage vorlesen", "lies die zwischenablage"),
        fr=("lis le presse-papiers", "lis ce que j'ai copié"),
        reply="",
    ),
    _c(
        "new_document",
        "New document",
        "app",
        "Open a blank document to paste or type into",
        en=("new document", "open new document", "new text"),
        ru=("новый документ", "новый текст"),
        de=("neues dokument", "neuer text"),
        fr=("nouveau document", "nouveau texte"),
        reply="",
    ),
    _c(
        "open_library",
        "Open library",
        "app",
        "Show the library",
        en=("open library", "library", "show library", "my documents", "show my papers"),
        ru=("библиотека", "открой библиотеку", "мои документы"),
        de=("bibliothek", "öffne die bibliothek", "meine dokumente"),
        fr=("bibliothèque", "ouvre la bibliothèque", "mes documents"),
        reply="",
    ),
    _c(
        "dark_mode",
        "Dark mode",
        "app",
        "Switch to the dark theme",
        en=("dark mode", "dark theme", "night mode", "lights off"),
        ru=("тёмная тема", "темная тема", "ночной режим"),
        de=("dunkler modus", "dunkles design", "nachtmodus"),
        fr=("mode sombre", "thème sombre"),
        reply="",
    ),
    _c(
        "light_mode",
        "Light mode",
        "app",
        "Switch to the light theme",
        en=("light mode", "light theme", "day mode", "lights on"),
        ru=("светлая тема", "дневной режим"),
        de=("heller modus", "helles design", "tagmodus"),
        fr=("mode clair", "thème clair"),
        reply="",
    ),
    _c(
        "show_commands",
        "What can I say",
        "app",
        "Show the list of voice commands",
        en=("what can i say", "help", "show commands", "list commands", "voice commands"),
        ru=("что можно сказать", "помощь", "покажи команды", "список команд"),
        de=("was kann ich sagen", "hilfe", "zeige befehle"),
        fr=("que puis-je dire", "aide", "montre les commandes"),
        reply="Here are the commands",
    ),
    _c(
        "stop_listening",
        "Stop listening",
        "app",
        "Turn the microphone off",
        en=("stop listening", "go to sleep", "microphone off", "mic off", "that's all"),
        ru=("перестань слушать", "выключи микрофон", "спать"),
        de=("hör auf zuzuhören", "mikrofon aus", "schlafen"),
        fr=("arrête d'écouter", "coupe le micro", "dors"),
        reply="Microphone off",
    ),
)

BY_ID: dict[str, Command] = {c.id: c for c in CATALOG}

# Actions a custom command may chain, with the parameter each takes (if any).
MACRO_ACTIONS: dict[str, str | None] = {
    "play": None,
    "pause": None,
    "resume": None,
    "stop": None,
    "repeat": None,
    "start_over": None,
    "next_sentence": None,
    "previous_sentence": None,
    "next_paragraph": None,
    "previous_paragraph": None,
    "next_section": None,
    "go_to_section": "number",
    "read_abstract": None,
    "set_speed": "number",
    "normal_speed": None,
    "faster": None,
    "slower": None,
    "louder": None,
    "quieter": None,
    "set_volume": "number",
    "mute": None,
    "unmute": None,
    "switch_voice": "voice",
    "next_voice": None,
    "set_pitch": "number",
    "where_am_i": None,
    "time_left": None,
    "summarize": None,
    "read_clipboard": None,
    "open_library": None,
    "dark_mode": None,
    "light_mode": None,
    "show_commands": None,
    "stop_listening": None,
    "say": "text",
}
